# Generated by Django 5.0.6 on 2024-06-16 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/products/')),
                ('price_cents', models.IntegerField()),
                ('keywords', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'product',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplianceProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.product')),
                ('type', models.CharField(default='appliance', max_length=100)),
                ('warranty_link', models.CharField(default='images/products/appliance-warranty.png', max_length=255)),
                ('instruction_link', models.CharField(default='images/products/appliance-instructions.png', max_length=255)),
            ],
            options={
                'db_table': 'applianceproducts',
            },
            bases=('ecommerce.product',),
        ),
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.product')),
                ('type', models.CharField(default='clothing', max_length=100)),
            ],
            options={
                'db_table': 'clothingproducts',
            },
            bases=('ecommerce.product',),
        ),
    ]
