# Generated by Django 5.0.6 on 2024-06-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_applianceproduct_clothingproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='images/products/', max_length=255),
        ),
    ]
